site_name: AWS Certification Study Guide
site_description: Guia de estudos para certificações AWS na área de IA/ML
site_author: William

theme:
  name: material
  icon:
    logo: material/robot-outline
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Alternar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Alternar para o modo claro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tooltips

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

nav:
  - Início: resumo.md
  - Meu Resumo: meu_resumo.md
  - Domínios AWS:
      - Domínio 4 - IA Responsável: Dominios/4.Diretrizes de IA Responsável.md
  - Serviços AWS:
      - Amazon SageMaker: Servicos/sagemaker.md