site_name: AWS Certification Study Guide
site_description: Guia de estudos para certificações AWS na área de IA/ML
site_author: William

theme:
  name: material
  icon:
    logo: material/robot-outline
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Alternar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Alternar para o modo claro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tooltips

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

nav:
  - Início: resumo.md
  - Domínios AWS:
      - "Domínio 1 - Fundamentos de IA e Machine Learning": Dominios/1.Fundamentals_IA_Machine_Learning.md
      - "Domínio 2 - Fundamentos de IA Generativa": "Dominios/2.Fundamentos de ia generativa.md"
      - "Domínio 3 - Prompt Engineering": "Dominios/3.Prompt Enginnering.md"
      - "Domínio 4 - Diretrizes de IA Responsável": "Dominios/4.Diretrizes de IA Responsável.md"
      - "Domínio 4 - Responsabilidades em IA": Dominios/4.Responsibilities_AI.md
      - "Domínio 5 - Aplicação de Modelos de Fundação": "Dominios/5.Aplicacao de Modelos de fundacao.md"
      - "Domínio 6 - Segurança e Governança": Dominios/6.Seguranca_Governanca.md
      - "Domínio 7 - Todos os Serviços": Dominios/7.todos_os_servicos.md
      - "Domínio 8 - Métricas": Dominios/8.Metricas.md
      - "Domínio 9 - Algoritmos de ML": "Dominios/9.Algorimos de ML.md"
      - "Domínio 10 - Bedrock": Dominios/10.Bedrock
  - Serviços AWS:
      - Amazon SageMaker: Servicos/sagemaker.md
