site_name: AWS Certification Study Guide
site_description: Guia de estudos para certificações AWS na área de IA/ML
site_author: William

theme:
  name: material
  icon:
    logo: material/robot-outline
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Alternar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Alternar para o modo claro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tooltips

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

nav:
  - Início: index.md
  - 'Domínio 1: Fundamentos de IA e ML':
      - IA & ML: Dominio_1_Fundamentos_IA_ML/1.Fundamentals_IA_Machine_Learning.md
  - 'Domínio 2: IA Generativa':
      - Fundamentos: Dominio_2_Fundamentos_IA_Generativa/2.Fundamentos de ia generativa.md
      - Prompt Engineering: Dominio_2_Fundamentos_IA_Generativa/3.Prompt Enginnering.md
  - 'Domínio 3: Modelos de Base':
      - Aplicação: Dominio_3_Aplicacoes_Modelos_Base/5.Aplicacao de Modelos de fundacao.md
      - Serviços de IA: Dominio_3_Aplicacoes_Modelos_Base/6.Servicos de IA.md
  - 'Domínio 4: IA Responsável':
      - Diretrizes: Dominio_4_Diretrizes_IA_Responsavel/4.Responsibilities_AI.md
  - 'Domínio 5: Sec., Conf. e Gov.':
      - Segurança, Conformidade e Governança: Dominio_5_Seguranca_Conformidade_Governanca/1.Seguranca_Governanca.md
  - Serviços AWS:
      - Todos os Serviços: Servicos/services_aws.md
      - Amazon Bedrock: Servicos/bedrock.md
      - Amazon SageMaker: Servicos/sagemaker.md
      - Amazon Q Developer: Servicos/amazon_q_developer.md
      - Outros Serviços: Servicos/outros.md
